### ISSUE TITLE
Advanced CLI Command: Create controller

### ISSUE THREAD

**Issue by saiforceone** [saiforceone/dirt-cli#39]
## Description

Creates a Django "app" within the main project with a predefined template, model file and default view

### Tasks

- [x] Replace `exec` command with `create-controller`
- [x] Add check for valid app name (can use existing function for validating project names)
- [x] Define default `django` view that passes props to the inertia page
- [x] Create function to write contents of the new `views.py` file
- [x] Set up `urls` file that has the correct urls and use it override generated `urls.py` file for the created app
- [x] output entry to be added to main `urls.py` file

* The Page template created should be placed in `<react|vue_fe_folder>/src/pages/<controller_name>/Index.{tsx|vue}`

#### React
- [x] Define Inertia Page template
- [x] Define default model
- [x] Create function to copy files to target directory

#### Vue.js
- [x] Define Inertia Page template
- [x] Define default model
- [x] Create function to copy files to target directory

**Comment by saiforceone** [comment]
![image](https://github.com/saiforceone/dirt-cli/assets/97003335/5e41f943-aaf0-4358-ac65-d0effe4a98ad)
This is what the command output looks like
